# .gitlab-ci.yml file to be placed in the root of your repository

image: node:14.18.1

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - mv dist/* public/
  artifacts:
    paths:
      - public/
  only:
    - dev
