# .gitlab-ci.yml file to be placed in the root of your repository

image: node:14.18.1

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - echo "########## Ejecutando comandos para paso antes de todo (before_script)"
  - npm install
  - ls -lsa

build:
  stage: build
  script:
    - echo "########## Ejecutando comandos para paso build"
    - ls -lsa
    - npm run build
    - mv public/ public_original/
    - ls -lsa

deploy:
  stage: deploy
  script:
    - echo "########## Ejecutando comandos para paso deploy"
    - ls -lsa
    - mkdir public/
    - mv dist/* public/
  artifacts:
    paths:
      - public/
  only:
    - dev
