version: "3"

services:
  # Proyecto de MEVN
  service_app:
    container_name: service_app
    build:
      context: ./tictoc-regina-app
      dockerfile: tictoc-regina-app.Dockerfile
    ports:
      - "3066:80"