@api = http://localhost:3069/api/v1/tictoc-clubregina/auth

@_id = 643c3a8a1b8c59afd5353aba

### Hacer prueba
GET {{api}}/test
Access-Control-Allow-Origin: http://localhost:3066
Content-Type: application/json

{
    "msg" : "Esto es una prueba"
}

### Registar un empleado
POST {{api}}/registrar
Access-Control-Allow-Origin: http://localhost:3066
Content-Type: application/json

{
    "nombres": "Developer", 
    "apellidos": "Developer", 
    "departamento": "Developer",
    "numero_colaborador" : "01",
    "correo" : "dev-01@example.com",
    "contrasenha" : "secret"    
}

### Ingresar con un empleado
POST {{api}}/ingresar
Access-Control-Allow-Origin: http://localhost:3066
Content-Type: application/json

{
    "numero_colaborador" : "01",
    "contrasenha" : "secret"    
}
